<?php  if ( ! defined('BASEPATH')) exit('No direct script access allowed');
$config['base_url'] = base_url('admin/dashboard/index');
$config['per_page'] = 10;
$config['uri_segment'] = 4;
$config['total_rows'] = 40;
$config['reuse_query_string'] = FALSE;
$config['use_page_numbers'] = TRUE;

$config['full_tag_open'] = '<li>';
$config['full_tag_close'] = '</li>';
$config['cur_tag_open'] = '<li><a href="javascript:void(0)">';
$config['cur_tag_close'] = '</a></li>';
$config['num_tag_open'] = '<li>';
$config['num_tag_close'] = '</li>';
$config['prev_tag_open'] = '<li>';
$config['prev_tag_close'] = '</li>';
$config['next_tag_open'] = '<li>';
$config['next_tag_close'] = '</li>';
$config['last_tag_open'] = '<li>';
$config['last_tag_close'] = '</li>';
$config['first_tag_open'] = '<li>';
$config['first_tag_close'] = '</li>';